# Generated by Django 5.2.6 on 2025-10-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_panel', '0007_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
