# Generated by Django 5.2.6 on 2025-09-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('login_signup', '0002_user_first_name_user_last_name_user_profile_pic_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='login_signup.user'),
        ),
    ]
