# Generated by Django 5.2.6 on 2025-09-22 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_options_message_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('preferences', 'User Preferences'), ('communication_style', 'Communication Style'), ('expertise_level', 'Expertise Level'), ('response_preferences', 'Response Preferences')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analysis',
                'verbose_name_plural': 'User Analyses',
                'unique_together': {('user', 'analysis_type')},
            },
        ),
    ]
