# Generated by Django 5.2.6 on 2025-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_useranalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranalysis',
            name='analysis_type',
            field=models.CharField(choices=[('sentiment', 'User Sentiment Analysis'), ('tone', 'Communication Tone'), ('topic', 'Topic Interest Analysis'), ('preference', 'User Preferences'), ('behavior', 'User Behavior Pattern'), ('engagement', 'User Engagement Level'), ('user_needs', 'User Needs Assessment'), ('communication_style', 'Communication Style'), ('expertise_level', 'Expertise Level'), ('response_preferences', 'Response Preferences')], max_length=50),
        ),
    ]
