# Generated by Django 5.2.6 on 2025-09-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_resulttable_result_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
