# Generated by Django 5.2.6 on 2025-10-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_uploaded_at_uploadedfile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='selected_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='target_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
