# Generated by Django 5.2.6 on 2025-10-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_uploadedfile_message_uploadedfile_selected_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='ai_response',
            new_name='gemini_recommendation',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='result_json',
            new_name='prediction_data',
        ),
    ]
