# Generated by Django 5.2.6 on 2025-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
